{
 "title": "Orchestrator",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Время выполнения по роботам",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  (\"StartedAt\" - interval '3 hours') AS \"time\",\n  (\n    abs(\n      extract(\n        second\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) + extract(\n        minute\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) * 60 + extract(\n        hour\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) * 60 * 60 + extract(\n        day\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) * 60 * 60 * 24\n    )\n  ) AS \"Duration\",\n  (\n    SELECT\n      \"Name\" AS \"Robot\"\n    FROM\n      public.\"Robots\"\n    WHERE\n      (\"Id\" = public.\"RpaProjectLaunches\".\"RobotId\")\n  ),\n  (\n    SELECT\n      \"Disabled\"\n    FROM\n      public.\"Robots\"\n    WHERE\n      (\"Id\" = public.\"RpaProjectLaunches\".\"RobotId\")\n  )\nFROM\n  public.\"RpaProjectLaunches\"\nWHERE\n  $__timeFilter(\"StartedAt\" - interval '3 hours')"
    }
   ]
  },
  {
   "title": "Общее время работы по роботам",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "SELECT\n(SELECT \"Name\" AS \"Robot\" FROM public.\"Robots\" WHERE \"Id\" = public.\"RpaProjectLaunches\".\"RobotId\"),\n(SELECT \"Name\" AS \"Project\" FROM public.\"RpaProjects\" WHERE \"Id\" = public.\"RpaProjectLaunches\".\"ProjectId\"),\n(SELECT \"Name\" AS \"Assignment\" FROM public.\"Assignments\" WHERE \"Id\" = public.\"RpaProjectLaunches\".\"AssignmentId\"),\n(\"StartedAt\" - interval '3 hours') AS StartedAt, (\n  abs( extract( second from (\"CompletedAt\" - \"StartedAt\") )\n + extract( minute from (\"CompletedAt\" - \"StartedAt\") ) * 60\n + extract( hour from (\"CompletedAt\" - \"StartedAt\") ) * 60 * 60\n + extract( day from (\"CompletedAt\" - \"StartedAt\") ) * 60 * 60 * 24)\n) AS \"Duration\", \"Success\"\nFROM public.\"RpaProjectLaunches\"\nWHERE\n  $__timeFilter((\"StartedAt\" - interval '3 hours'))\nORDER BY \"StartedAt\" DESC"
    }
   ]
  },
  {
   "title": "Время выполнения по проектам",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  (\"StartedAt\" - interval '3 hours') AS \"time\",\n  (\n    abs(\n      extract(\n        second\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) + extract(\n        minute\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) * 60 + extract(\n        hour\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) * 60 * 60 + extract(\n        day\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) * 60 * 60 * 24\n    )\n  ) AS \"Duration\",\n  (\n    SELECT\n      \"Name\" AS \"Project\"\n    FROM\n      public.\"RpaProjects\"\n    WHERE\n      (\"Id\" = public.\"RpaProjectLaunches\".\"ProjectId\")\n  ),\n  (\n    SELECT\n      \"Disabled\"\n    FROM\n      public.\"RpaProjects\"\n    WHERE\n      (\"Id\" = public.\"RpaProjectLaunches\".\"ProjectId\")\n  )\nFROM\n  public.\"RpaProjectLaunches\"\nWHERE\n  $__timeFilter(\"StartedAt\" - interval '3 hours')"
    }
   ]
  },
  {
   "title": "Общее время работы по проектам",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  (\n    SELECT\n      \"Name\" AS \"Robot\"\n    FROM\n      public.\"Robots\"\n    WHERE\n      \"Id\" = public.\"RpaProjectLaunches\".\"RobotId\"\n  ),\n  (\n    SELECT\n      \"Name\" AS \"Project\"\n    FROM\n      public.\"RpaProjects\"\n    WHERE\n      \"Id\" = public.\"RpaProjectLaunches\".\"ProjectId\"\n  ),\n  (\n    SELECT\n      \"Name\" AS \"Assignment\"\n    FROM\n      public.\"Assignments\"\n    WHERE\n      \"Id\" = public.\"RpaProjectLaunches\".\"AssignmentId\"\n  ),\n  (\"StartedAt\" - interval '3 hours') AS StartedAt,\n  (\n    abs(\n      extract(\n        second\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) + extract(\n        minute\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) * 60 + extract(\n        hour\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) * 60 * 60 + extract(\n        day\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) * 60 * 60 * 24\n    )\n  ) AS \"Duration\",\n  \"Success\"\nFROM\n  public.\"RpaProjectLaunches\"\nWHERE\n  $__timeFilter((\"StartedAt\" - interval '3 hours'))\nORDER BY\n  \"StartedAt\" DESC"
    }
   ]
  },
  {
   "title": "Среднее время выполнения по проектам",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (\"StartedAt\" - interval '3 hours') AS \"time\",\n(\n  abs( extract( second from (\"CompletedAt\" - \"StartedAt\") )\n + extract( minute from (\"CompletedAt\" - \"StartedAt\") ) * 60\n + extract( hour from (\"CompletedAt\" - \"StartedAt\") ) * 60 * 60\n + extract( day from (\"CompletedAt\" - \"StartedAt\") ) * 60 * 60 * 24)\n) AS \"Duration\",\n(SELECT \"Name\" AS \"Project\" FROM public.\"RpaProjects\" WHERE (\"Id\" = public.\"RpaProjectLaunches\".\"ProjectId\")),\n(SELECT \"Disabled\" FROM public.\"RpaProjects\" WHERE (\"Id\" = public.\"RpaProjectLaunches\".\"ProjectId\"))\nFROM\n  public.\"RpaProjectLaunches\"\nWHERE\n  $__timeFilter(\"StartedAt\" - interval '3 hours')"
    }
   ]
  },
  {
   "title": "Общее время работы",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n(SELECT \"Name\" AS \"Robot\" FROM public.\"Robots\" WHERE \"Id\" = public.\"RpaProjectLaunches\".\"RobotId\"),\n(SELECT \"Name\" AS \"Project\" FROM public.\"RpaProjects\" WHERE \"Id\" = public.\"RpaProjectLaunches\".\"ProjectId\"),\n(SELECT \"Name\" AS \"Assignment\" FROM public.\"Assignments\" WHERE \"Id\" = public.\"RpaProjectLaunches\".\"AssignmentId\"),\n(\"StartedAt\" - interval '3 hours') AS StartedAt, (\n  abs( extract( second from (\"CompletedAt\" - \"StartedAt\") )\n + extract( minute from (\"CompletedAt\" - \"StartedAt\") ) * 60\n + extract( hour from (\"CompletedAt\" - \"StartedAt\") ) * 60 * 60\n + extract( day from (\"CompletedAt\" - \"StartedAt\") ) * 60 * 60 * 24)\n) AS \"Duration\", \"Success\"\nFROM public.\"RpaProjectLaunches\"\nWHERE\n  $__timeFilter((\"StartedAt\" - interval '3 hours'))\nORDER BY \"StartedAt\" DESC"
    }
   ]
  },
  {
   "title": "Количество одновременно работающих роботов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  (\"SA\" - interval '3 hours') AS \"SA\",\n  (\n    SELECT\n      COUNT(*)\n    FROM\n      public.\"RpaProjectLaunches\"\n    WHERE\n      \"SA\" BETWEEN \"StartedAt\"\n      AND \"CompletedAt\"\n  ) AS \"Workers\"\nFROM\n  (\n    SELECT\n      \"StartedAt\" AS \"SA\",\n      \"StartedAt\",\n      \"CompletedAt\"\n    FROM\n      public.\"RpaProjectLaunches\"\n    WHERE\n      \"CompletedAt\" IS NOT null\n  ) AS \"Completed\"\nWHERE\n  $__timeFilter(\"SA\" - interval '3 hours')\nGROUP BY\n  \"SA\"\nORDER BY\n  \"SA\" DESC"
    }
   ]
  },
  {
   "title": "Выполнение по всем роботам",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) AS \"Success\"\nFROM\n  public.\"RpaProjectLaunches\"\nWHERE\n  $__timeFilter(\"StartedAt\" - interval '3 hours') AND \"Success\" = true"
    },
    {
     "rawSql": "SELECT COUNT (*) AS \"Fail\"\nFROM\n  public.\"RpaProjectLaunches\"\nWHERE\n  $__timeFilter(\"StartedAt\" - interval '3 hours') AND \"Success\" = false"
    },
    {
     "rawSql": "SELECT COUNT (*) AS \"In progress\"\nFROM\n  public.\"RpaProjectLaunches\"\nWHERE\n  $__timeFilter(\"StartedAt\" - interval '3 hours') AND \"Success\" IS NULL"
    }
   ]
  },
  {
   "title": "Неуспешное выполнение по проектам",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT (\"StartedAt\" - interval '3 hours') AS \"time\", \"Success\" AS \".\",\n(SELECT \"Name\" AS \"Project\" FROM public.\"RpaProjects\" WHERE (\"Id\" = public.\"RpaProjectLaunches\".\"ProjectId\")),\n(SELECT \"Disabled\" FROM public.\"RpaProjects\" WHERE (\"Id\" = public.\"RpaProjectLaunches\".\"ProjectId\"))\nFROM\n  public.\"RpaProjectLaunches\"\nWHERE\n  $__timeFilter(\"StartedAt\" - interval '3 hours') AND \"Success\" != true"
    }
   ]
  },
  {
   "title": "Успешное выполнение по проектам",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT (\"StartedAt\" - interval '3 hours') AS \"time\", \"Success\" AS \"Pr\",\n(SELECT \"Name\" AS \"Project\" FROM public.\"RpaProjects\" WHERE (\"Id\" = public.\"RpaProjectLaunches\".\"ProjectId\")),\n(SELECT \"Disabled\" FROM public.\"RpaProjects\" WHERE (\"Id\" = public.\"RpaProjectLaunches\".\"ProjectId\"))\nFROM\n  public.\"RpaProjectLaunches\"\nWHERE\n  $__timeFilter(\"StartedAt\" - interval '3 hours') AND \"Success\" = true"
    }
   ]
  },
  {
   "title": "История запусков",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  (\n    SELECT\n      \"Name\" AS \"Robot\"\n    FROM\n      public.\"Robots\"\n    WHERE\n      \"Id\" = public.\"RpaProjectLaunches\".\"RobotId\"\n  ),\n  (\n    SELECT\n      \"Name\" AS \"Project\"\n    FROM\n      public.\"RpaProjects\"\n    WHERE\n      \"Id\" = public.\"RpaProjectLaunches\".\"ProjectId\"\n  ),\n  (\n    SELECT\n      \"Name\" AS \"Assignment\"\n    FROM\n      public.\"Assignments\"\n    WHERE\n      \"Id\" = public.\"RpaProjectLaunches\".\"AssignmentId\"\n  ),\n  (\"StartedAt\" - interval '3 hours') AS StartedAt,\n  (\n    abs(\n      extract(\n        second\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) + extract(\n        minute\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) * 60 + extract(\n        hour\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) * 60 * 60 + extract(\n        day\n        from\n          (\"CompletedAt\" - \"StartedAt\")\n      ) * 60 * 60 * 24\n    )\n  ) AS \"Duration\",\n  \"Success\"\nFROM\n  public.\"RpaProjectLaunches\"\nWHERE\n  $__timeFilter((\"StartedAt\" - interval '3 hours'))\nORDER BY\n  \"StartedAt\" DESC"
    }
   ]
  }
 ]
}